# This docker compose file is intended for development. 
services:
  eer_ros_packages:
    build: 
      context: ./ros_workspace
      dockerfile: Dockerfile
      args:
      - ROV_NAME=${ROV_NAME:-waterwitch} # Specify the name of the ROV 
      - DEV_MODE=${DEV_MODE:-true} # Set DEV_MODE to 1 (simulated ROV)
    tty: true
    container_name: eer_ros_packages
    restart: always
    network_mode: host # Run in host mode to allow ros2 communication with host network
    ipc: host # Required for ros2 communication with host network
    volumes:
      - ./ros_workspace/configs:/app/configs # Mount the config directory so that it persists between container restarts
  web_frontend: 
    build: ./web_frontend
    container_name: web_frontend
    restart: always
    tty: true
    ports:
     - "80:80"
