# This docker compose file is intended for development. 
services:
  backend:
    build: 
      context: ./ROS2
      dockerfile: DevDockerfile
    tty: true
    container_name: backend
    restart: always
    network_mode: host # Run in host mode to allow ros2 communication with host network
    ipc: host # Required for ros2 communication with host network
    volumes:
      - ./ROS2/colcon_ws/config.db:/app/config.db
      - ./ROS2/colcon_ws/tasks.db:/app/tasks.db
  web_frontend: 
    build: ./WebGUI
    restart: always
    tty: true
    ports:
     - "80:80"
