# This docker compose file is intended for development. 
services:
  backend:
    build: 
      context: ./ROS2
      dockerfile: DevDockerfile
    tty: true
    container_name: backend
    restart: always
    network_mode: host # Run in host mode to allow ros2 communication with host network
    ipc: host # Required for ros2 communication with host network
    volumes:
      - ./ROS2/ROS_workspace/src/beaumont_pkg/beaumont_pkg/config:/app/src/beaumont_pkg/beaumont_pkg/config # Mount the config directory so that it persists between container restarts
  web_frontend: 
    build: ./WebGUI
    restart: always
    tty: true
    ports:
     - "80:80"
